Normal-OJ/Back-End

mongo/engine.py

add course's db on the new branch

Submission course

---

model/course.py
model/utils/request.py
mongo/course.py
mongo/engine.py
mongo/utils.py
tests/test_course.py

完成了course的部分，但unit tests和之前說的displayedName還沒加

Course finished

---

model/submission.py
mongo/submission.py
tests/test_submission.py

WIP, still missing some function and testcase about homework, contest, problem

[WIP] Submission API

---

app.py
model/__init__.py
model/post.py
mongo/__init__.py
mongo/engine.py
mongo/post.py
tests/test_post.py

complete Post

---

model/submission.py
mongo/engine.py
mongo/inbox.py
mongo/submission.py
tests/conftest.py
tests/test_submission.py

Able to limit size of user uploaded file now

size limit

---

create_users.py
model/submission.py
mongo/engine.py
mongo/submission.py
mongo/user.py
tests/test_submission.py

some enhancement about submission module

submission opt

---

model/problem.py
mongo/engine.py
mongo/submission.py
tests/base_tester.py
tests/test_problem.py
tests/test_submission.py

add route for getting highest score of problem

High score

---

model/submission.py
mongo/submission.py
tests/src/main2.pdf
tests/test_submission.py

* fix submitting ValidationError's response

submitting check pdf's file type now

---

gunicorn.conf.dev.py
model/problem.py
model/submission.py
mongo/contest.py
mongo/engine.py
mongo/homework.py
mongo/problem.py
mongo/problem/__init__.py
mongo/problem/exception.py
mongo/problem/problem.py
mongo/problem/test_case.py
mongo/submission.py
mongo/utils.py
tests/conftest.py
tests/test_problem.py
tests/test_submission.py
tests/unittest/test_problem.py
tests/utils/problem.py

Related: Normal-OJ/Normal-OJ#25
之後需要讓沙盒也可以接受不同格式的輸入。

Allow multiple files placed under test case

---

model/course.py
model/problem.py
model/submission.py
mongo/course.py
mongo/problem/problem.py
mongo/submission.py

Issue #167 
- Integrate permission control and use capability to access api route
- modules: submission, problem, course

Refactor permission capability

---

model/auth.py
mongo/user.py
mongo/utils.py
tests/base_tester.py
tests/conftest.py
tests/test_auth.py
tests/test_homework.py

feat: force batch signup

---

model/course.py
tests/test_course.py
tests/test_homework.py

fix: permission check for course scoreboard

---

tests/test_use_announcement.py

Tested files:
- `model/announcement.py`
- `mongo/announcement.py`

test: add test cases for announcement to reach 100% statement coverage.

---

model/copycat.py
tests/test_copycat.py

Fix #226 
2 tested routes:
- GET `/copycat`
- POST `/copycat`
3 tested helper functions:
- `is_valid_url`
- `get_report_task`
- `get_report_by_url`

test: add test cases for `model/copycat.py` to reach 100% statement coverage.

---

tests/test_course.py

Fix: #230 
Tested files:
- `model/course.py`
- `mongo/course.py`

test: add test cases for course to reach 100% statement coverage.

---

model/post.py
tests/test_post.py

Fix: #237 
Tested files:
- `model/post.py`
- `mongo/post.py`

test: add test cases for post to reach 100% statement coverage.

---

model/profile.py
tests/test_profile.py

test: remove unuseful feature code, add test case to cover `profile.py`

---

model/utils/smtp.py
tests/test_smtp.py

test: add test cases for smtp.send()

---

model/auth.py
mongo/user.py
tests/test_auth.py

test: add test cases to cover mongo/user.py

---

model/utils/request.py
tests/test_utils_request.py

Fix: #243 
Tested file:
- `model/utils/request.py`

test: add test cases for Request to reach 100% statement coverage.

---

model/submission.py
mongo/submission.py
tests/test_submission.py
tests/unittest/submission/test_check_code.py
tests/unittest/submission/test_filter.py
tests/utils/submission.py

test: add some test cases for submission

---

tests/test_problem.py

test: add test cases for `mongo/sandbox.py`

---

tests/test_problem.py

test: add test cases for `mongo/base.py` to reach 100% coverage

---

mongo/ip_filter.py
tests/test_ip_filter.py

test: add test cases for `mongo/ip_filter.py` to reach 100% coverage

---

tests/test_submission.py
tests/unittest/submission/test_get_output.py

test(submission): add test cases for get_single_output

---

mongo/engine.py
tests/test_mongo_engine.py

test: add test cases for `mongo/engine.py` to reach 100% statement coverage

---

model/announcement.py
model/copycat.py
model/post.py
model/problem.py
model/submission.py
mongo/announcement.py
mongo/homework.py
mongo/post.py
mongo/problem/problem.py
mongo/submission.py
tests/test_get_homewrok_problem.py
tests/unittest/test_problem.py

Feat auto open problem

---

README.md
app.py
model/auth.py
model/utils/smtp.py
pyproject.toml
pytest.ini
tests/test_auth.py

feat: make host configurable

---

mongo/user.py
tests/test_auth.py

我們不該記 user_id，改記 user.id 才對。
Update #287

fix: record ip
